[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:$PORT"
