[phases.setup]
nixPkgs = ["python311", "pkg-config", "mysql80"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn portfolio_project.wsgi --bind 0.0.0.0:$PORT"
