services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py compress --force
      python manage.py migrate
      python manage.py setup_production_data
    startCommand: gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings.production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: COMPRESS_ENABLED
        value: True
      - key: COMPRESS_OFFLINE
        value: True

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio
    plan: free
