services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory: $(pwd)"
      echo "Files in static directory:"
      ls -la static/ || echo "No static directory found"
      echo "Django settings module: $DJANGO_SETTINGS_MODULE"
      echo "Testing Cloudinary configuration:"
      python manage.py test_cloudinary
      python manage.py collectstatic --noinput --clear --verbosity=2
      echo "Collectstatic completed"
      python manage.py migrate
      echo "Migration completed"
    startCommand: gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings.production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: USE_CLOUDINARY
        value: True
      - key: CLOUDINARY_CLOUD_NAME
        value: de9i7id2b
      - key: CLOUDINARY_API_KEY
        value: 547248818221456
      - key: CLOUDINARY_API_SECRET
        value: 611drBROvgh5Bkip4HZYaLRoddI
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio
    plan: free
