services:
  - type: web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn portfolio_project.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings.production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: USE_CLOUDINARY
        value: True
      - key: CLOUDINARY_CLOUD_NAME
        value: de9i7id2b
      - key: CLOUDINARY_API_KEY
        value: 547248818221456
      - key: CLOUDINARY_API_SECRET
        value: 611drBROvgh5Bkip4HZYaLRoddI
      - key: DJANGO_SECRET_KEY
        sync: false                # managed via dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: ALLOWED_HOSTS
        value: your-render-domain.onrender.com

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio
    plan: free
