# Generated by Django 5.2.1 on 2025-07-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
