# Generated by Django 5.2.1 on 2025-07-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_testimonial_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated list of tags", max_length=500
            ),
        ),
    ]
