# Generated by Django 4.2.11 on 2025-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_blogpost_is_featured_blogpost_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_forks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="github_language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="github_repo",
            field=models.CharField(
                blank=True,
                help_text="GitHub repository name (e.g., username/repo-name)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="github_stars",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="github_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_github_synced",
            field=models.BooleanField(
                default=False, help_text="Automatically sync from GitHub"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/projects/"),
        ),
    ]
