# Generated by Django 4.2.11 on 2025-07-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_personalinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Your location (e.g., City, Country)",
                max_length=100,
            ),
        ),
    ]
