# Generated by Django 4.2.11 on 2025-07-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_personalinfo_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("date_received", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Academic, Professional, Community",
                        max_length=100,
                    ),
                ),
                (
                    "award_image",
                    models.ImageField(blank=True, upload_to="images/awards/"),
                ),
                (
                    "award_url",
                    models.URLField(blank=True, help_text="Link to award details"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-date_received"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Leave blank if no expiry", null=True
                    ),
                ),
                ("credential_id", models.CharField(blank=True, max_length=200)),
                (
                    "credential_url",
                    models.URLField(
                        blank=True, help_text="Link to verify certification"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "certificate_image",
                    models.ImageField(blank=True, upload_to="images/certifications/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=200)),
                (
                    "degree",
                    models.CharField(
                        help_text="e.g., Bachelor of Science in Computer Science",
                        max_length=200,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(
                        blank=True, help_text="e.g., Computer Science", max_length=200
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently enrolled",
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="e.g., First Class, 3.8 GPA",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about your education"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "is_current",
                    models.BooleanField(default=False, help_text="Currently enrolled"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (0 = first)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Homepage"),
                            ("about", "About Page"),
                            ("projects", "Projects Page"),
                            ("blog", "Blog Page"),
                            ("contact", "Contact Page"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="SEO title (60 chars max)", max_length=60
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Meta description (160 chars max)", max_length=160
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=255
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, help_text="Open Graph title", max_length=60
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True, help_text="Open Graph description", max_length=160
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Open Graph image",
                        upload_to="images/seo/",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="about_intro",
            field=models.TextField(
                blank=True, help_text="Introduction paragraph for About page"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="current_role",
            field=models.CharField(
                blank=True, help_text="Current job title/role", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="interests",
            field=models.TextField(
                blank=True, help_text="Personal interests and hobbies"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta description for homepage",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="meta_keywords",
            field=models.CharField(
                blank=True, help_text="SEO keywords (comma-separated)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="professional_summary",
            field=models.TextField(
                blank=True, help_text="Professional journey summary"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="soft_skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of soft skills"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="technical_skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of technical skills"
            ),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="years_experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Years of professional experience"
            ),
        ),
    ]
