# Generated by Django 4.2.11 on 2025-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_award_certification_education_seosettings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "company_url",
                    models.URLField(blank=True, help_text="Company website URL"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("fulltime", "Full-time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="fulltime",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if current position",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Currently working here"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Describe your role, responsibilities, and achievements"
                    ),
                ),
                (
                    "technologies",
                    models.TextField(
                        blank=True, help_text="Technologies used (comma-separated)"
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Key achievements and accomplishments"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (0 = most recent)"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "url",
                    models.URLField(
                        help_text="Internal URL (e.g., /about/) or external URL (e.g., https://github.com)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quick", "Quick Links"),
                            ("services", "Services"),
                            ("resources", "Resources"),
                            ("social", "Social Media"),
                            ("legal", "Legal"),
                        ],
                        default="quick",
                        max_length=20,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS icon class (e.g., bi bi-house)",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_external",
                    models.BooleanField(default=False, help_text="Opens in new tab"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Front-End Development"),
                            ("backend", "Back-End Development"),
                            ("tools", "Tools & Technologies"),
                            ("devops", "DevOps & Cloud"),
                            ("database", "Database Technologies"),
                            ("mobile", "Mobile Development"),
                            ("other", "Other Skills"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        default=3, help_text="Skill level 1-5 (1=Beginner, 5=Expert)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of your experience with this skill",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for skill icon (e.g., fab fa-python)",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show prominently on homepage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "order", "name"],
                "unique_together": {("name", "category")},
            },
        ),
    ]
