# Generated by Django 4.2.11 on 2025-08-14 10:33

from django.db import migrations, models
import portfolio_project.storages


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_careertimeline_footerlink_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Upload your resume/CV (PDF, DOC, DOCX). Stored on Railway volume for reliable access.",
                storage=portfolio_project.storages.ResumeStorage(),
                upload_to="resumes/",
            ),
        ),
    ]
