# Generated by Django 4.2.11 on 2025-08-14 11:28

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_personalinfo_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Upload your resume/CV (PDF, DOC, DOCX). Served directly from /media/ path.",
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/media/",
                    location=pathlib.PureWindowsPath("C:/Users/User/My Porfolio/media"),
                ),
                upload_to="resumes/",
            ),
        ),
    ]
