# Generated by Django 4.2.11 on 2026-10-05 06:56

from django.db import migrations, models
import portfolio_project.storages


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_personalinfo_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Upload your resume/CV (PDF, DOC, DOCX). Served directly from /media/ path.",
                storage=portfolio_project.storages.ResumeStorage(),
                upload_to="resumes/",
            ),
        ),
    ]
